version: "2"

services:
  api:
    build: ./api
    volumes:
      - "./api/src:/usr/src/app/src"
    ports:
      - "5000:5000"
  ui:
    build: ./ui
    volumes:
      - "./ui/src:/usr/src/app/src"
    ports:
      - "3000:3000"
    links:
      - "api:api"
